os: linux
dist: bionic
language: generic

jobs:
  include:
    - os: osx
      osx_image: xcode10.1
      env: SWIFT=4.2.1

    - os: osx
      osx_image: xcode10.2
      env: SWIFT=5.0.1

    - os: osx
      osx_image: xcode11.3
      env: SWIFT=5.1.3

    - os: linux
      env: SWIFT=4.2.4

    - os: linux
      env: SWIFT=5.0.3

    - os: linux
      env: SWIFT=5.1.4

before_install:
  - . Utilities/install-swift.sh

script:
  - /bin/bash Tests/test-script.sh
